version: '3.8'
services:
  db:
    image: postgres
    container_name: pgdb_ba
    restart: always
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '9300:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local